version: '3.9'

services:
  db:
    env_file:
      - ".env.dev"
    container_name: "database"
    image: "sameersbn/postgresql"
    networks:
      - botnet
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/config:/etc/postgresql
      - ./postgres/logs:/var/log/postgresql
      - ./postgres/lib:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - botnet

  bot:
    container_name: "hrlettersbot_dev"
    build:
      context: .
    networks:
      - botnet
    restart: always
    env_file:
      - ".env.dev"
    command: python app.py
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

  postcards_server:
    image: postcard_api
    container_name: "postcards"
    restart: always
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
